language: cpp
dist: focal
compiler:
  - gcc
os:
  - linux
branches:
  only:
    - master
before_install:
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo apt-get -q update
  - sudo apt-get -y install g++-10
  - sudo apt-get -y install python3-pip
  - pip3 install conan
  - export CXX=g++-10 CC=gcc-10
jobs:
  include:
    - stage: test
      script:
        - mkdir -p build
        - cd build
        - cmake -DCMAKE_BUILD_TYPE=Release ..
        - make
        - ctest
