language: cpp
dist: focal
os:
  - linux
branches:
  only:
    - master
jobs:
  include:
    - stage: Verification
      name: Format checker
      script:
        - scripts/check_format.sh
    - stage: Validation
      name: GNU Test
      script:
        - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
        - sudo apt-get -q update
        - sudo apt-get -y install g++-10
        - sudo apt-get -y install python3-pip
        - pip3 install conan
        - export CXX=g++-10 CC=gcc-10
        - mkdir -p build
        - cd build
        - cmake -DCMAKE_BUILD_TYPE=Release ..
        - make
        - ctest
    - stage: Validation
      name: CLANG Test
      script:
        - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
        - sudo apt-get -q update
        - sudo apt-get -y install clang++-10
        - sudo apt-get -y install python3-pip
        - pip3 install conan
        - export CXX=clang++-10 CC=clang-10
        - mkdir -p build
        - cd build
        - cmake -DCMAKE_BUILD_TYPE=Release ..
        - make
        - ctest
